### ISSUE TITLE
Randomly zooming out possible?

### ISSUE THREAD

**Issue by DeepVoltaire** [albu/albumentations#103]
Hi, if I would like to randomly zoom out my image like with iaa.Scale((0.5, 1.0)), how would I do this with albumentations? I could pad the image first, but the amount of padding would not be random. 

![image](https://user-images.githubusercontent.com/15069697/47145031-16592300-d2c9-11e8-8833-acbbe7335054.png)

**Comment by albu** [comment]
Hi, yes, it's possible. You can pass tuple to `RandomScale` or `ShiftScaleRotate` methods. https://albumentations.readthedocs.io/en/latest/api/augmentations.html#albumentations.augmentations.transforms.RandomScale

**Comment by albu** [comment]
Oh, sorry, actually you can try `ShiftScaleRotate` with `Shift` and `Rotate` both zeros. It should work as you want.

**Comment by DeepVoltaire** [comment]
Yes, that works! Thanks a lot. :)
