### ISSUE TITLE
Could not broadcast on Crop Images

### ISSUE THREAD

**Issue by MarioProjects** [albu/albumentations#115]
Hello, thank you very much for your work before anything else. I'm having problems applying random crops and center crops when going from a given shape to a smaller one obviously. Also happens with Resize(). The output is as follows:

![seleccion_001](https://user-images.githubusercontent.com/23385329/47715694-c1aa9600-dc40-11e8-894e-5d2a00c09261.png)
Outputs:

![seleccion_002](https://user-images.githubusercontent.com/23385329/47715700-c5d6b380-dc40-11e8-8bb7-f7d32f880d01.png)

Where original sample shape is (64,64,3)

**Comment by albu** [comment]
Hi, it probably happens because all pipeline runs with `probability_apply_transforms` so sometimes you are not doing `Resize`. `Compose` actually has `preprocessing args` so it's better to put this operation there. We are working on better `Compose` API to overcome this issues, stay tuned!

**Comment by MarioProjects** [comment]
Okay, I understand what you mean, sometimes you do not. I have tried out the compose and the crops work correctly. Now I am testing the Resize (also separately) and it is giving me problems, as well as the Normalize (when using black and white images of 1 channel) and Rotate.

![selection_001](https://user-images.githubusercontent.com/23385329/47928284-1579e100-dec6-11e8-93a9-98faf115795b.png)
![selection_002](https://user-images.githubusercontent.com/23385329/47928291-1874d180-dec6-11e8-87b4-d6a912110a32.png)
![selection_003](https://user-images.githubusercontent.com/23385329/47928295-1a3e9500-dec6-11e8-98de-9e57dad36031.png)

**Comment by MarioProjects** [comment]
Yeah sure! It is very easy to be my fault: D Trying to load some MNIST data and normalize them gives me the error that I mentioned earlier.

![selection_002](https://user-images.githubusercontent.com/23385329/47935435-917e2400-deda-11e8-9167-d78863c779bc.png)

**Comment by ternaus** [comment]
In this example, you are trying to apply Normalize with default parameters (3 channels) to a grayscale image with one channel.

**Comment by MarioProjects** [comment]
But then how should I do it? I've been looking at the documentation https://albumentations.readthedocs.io/en/latest/api/augmentations.html?highlight=normalize#albumentations.augmentations.transforms.Normalize and I do not know how to use it for a channel case.

On the other hand, the problem with Rotate and Resize also persists. Greetings.

**Comment by ternaus** [comment]
To apply Normalize to an image with a number of channels that is different from 3 you need to pass as parameters of the transformation `mean` and `std` that has the number of values equal to the number of channels in the image.
```
import albumentations as albu
import numpy as np

image = np.ones((5, 5))

aug = albu.Normalize(mean=(0.5), std=(0.2), p=1)
augmented_image = aug(image=image)['image']
```

**Comment by ternaus** [comment]
It is not completely clear what error do you get with Rotate and Resize?

Could you please share a minimal example of the code that reproduces the error? So that we would be able to run it on our computers? (Not a screenshot)

**Comment by MarioProjects** [comment]
Thanks for the Normalize! :D Around here it sounds a bit impersonal but I want you to know that I am very grateful for your work. I'm a little new here, I had to have passed code from the beginning.


```
import numpy as np
import albumentations

def apply_albumentation(aug, image):
    image = aug(image=image)['image']
    return image

sample = np.arange(0, 28*28).reshape(28,28)
sample_transformed = apply_albumentation(albumentations.Rotate(limit=1,p=1), sample)
```
Gives me: 

> error: OpenCV(3.4.3) /io/opencv/modules/imgproc/src/imgwarp.cpp:1805: error: (-215:Assertion failed) ifunc != 0 in function 'remap'

**Comment by ternaus** [comment]
`sample = np.arange(0, 28*28).reshape(28,28)`
returns an array with dtype `np.int64` which is not supported by OpenCV

Typically (not always) images are stored in the `np.uint8` with pixel values in the range [0, 255]

The two possible options:

1. `sample = np.arange(0, 28*28).reshape(28,28).astype(np.uint8)` if you are sure that your pixel values are in [0, 255]
2. `sample = np.arange(0, 28*28).reshape(28,28).astype(float)`

**Comment by MarioProjects** [comment]
Thank you so much then!!!!
