### ISSUE TITLE
exception in GridDistortion

### ISSUE THREAD

**Issue by adizhol** [albu/albumentations#134]
version: albumentations-0.1.7
call:
```
    distortion = albumentations.GridDistortion(num_steps=32, distort_limit=0.7, border_mode=cv2.BORDER_CONSTANT, p=0.3)
    sample = distortion(image=sample)['image']

```
image is 256x256x3

Thrown exception:

>   File "C:\Users\owner\AppData\Local\conda\conda\envs\allegro_env\lib\site-packages\albumentations\augmentations\functional.py", line 412, in grid_distortion
>     cur = prev + x_step * xsteps[idx]
> IndexError: list index out of range
>

**Comment by BloodAxe** [comment]
This seems not to be an issue on Albumentations@0.1.12. Therefore I'm closing it. If the problem persist feel free to re-open it and attach a test case for reproducing.

**Comment by delzac** [comment]
Hi, i receive this error too. Code below to reproduce it.

```
from albumentations import GridDistortion
from albumentations import Compose
import numpy as np
import cv2


augmentation = Compose([GridDistortion(num_steps=5, distort_limit=0.3, interpolation=cv2.INTER_LINEAR, border_mode=cv2.BORDER_CONSTANT, p=1)], p=1)

err_height = []
for i in range(200):
    try:
        image = np.random.random((i, 100))
        image = augmentation(image=image)['image']

    except Exception:
        err_height.append(image.shape)

print(err_height)
```

Output:
`[0, 1, 2, 3, 4, 7, 8, 9, 14]`

Seems like there are some special numbers. By increasing the num_steps, the number of special numbers increase too.

At num_steps = 10 we have 

Output:
`[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 12, 13, 14, 15, 16, 17, 18, 19, 24, 25, 26, 27, 28, 29, 36, 37, 38, 39, 48, 49]`
