### ISSUE TITLE
Can we use this library for 3D volumes?

### ISSUE THREAD

**Issue by vuralerdogan** [albu/albumentations#138]
Hi, thank you for this amazing library. I was wondering can we use this library for on 3D small volumes such as 64x64x64. Thank you for your time,
Vural

**Comment by vuralerdogan** [comment]
Can we rehape 3D volumes and apply this library then reshape it back?

**Comment by DecentMakeover** [comment]
@verdoganai Hi , How did you manage to augment your 3d data?

**Comment by ashawkey** [comment]
@DecentMakeover 
I wrote a simple 3D data augmentation package [here](https://github.com/ashawkey/volumentations) inspired by albumentations and batchgenerators, maybe you will find it helpful.

**Comment by DecentMakeover** [comment]
@ashawkey Amazing, Did it improve your results ?

**Comment by ashawkey** [comment]
@DecentMakeover Yes, but I'm new to 3D data and there maybe lots of things to test.

**Comment by tybrad11** [comment]
I second the need to apply the same transform to an array of images.

**Comment by Khoa-NT** [comment]
Please support 3D data augmentation.

**Comment by ekurtulus** [comment]
Yes, volumetric semantic segmentations require extensive data augmentation. It would be nice if 3D volumetric data augmentation is supported.
