### ISSUE TITLE
ShiftScaleRotate does not implement bbox transformation correctly

### ISSUE THREAD

**Issue by Anjum48** [albu/albumentations#151]
After augmentation, the boxes are no longer tight around the cat & dog. Is this normal for an affine transform?

![screenshot from 2018-12-21 11-07-34](https://user-images.githubusercontent.com/13783303/50331743-d4d73500-0510-11e9-9ca2-e843458d2390.png)

**Comment by Anjum48** [comment]
I think if there are only 4 points, this is normal behaviour for the affine transform at large angles. When there are more points available, the box is tighter and a better fit. Would it be worth adding another `format` field called something like `points` so that multiple x, y points are transformed before creating a box? 

This is a good dataset to test this on: https://www.kaggle.com/martinpiotte/bounding-box-model
However, this might be a bit niche since I'm not sure how many datasets this might be applicable to.

**Comment by albu** [comment]
Hi, so yes, we think it's normal for general bounding box (4 points). 
There is PR for multiple keypoints support: https://github.com/albu/albumentations/pull/145
