### ISSUE TITLE
Does it support multiple channels?(>3 channels)

### ISSUE THREAD

**Issue by Se7enZHOU** [albu/albumentations#152]
I stack 4 single-channel image to a 4-D image and transform it. It fails.

How to transform a image more than 3 channels?

Or is there some method to transform the 4 single-channel image with the same random transformation?

**Comment by BloodAxe** [comment]
Hi. Partially yes. Due to their nature, some augmentations are intended for RGB images (For instance CLAHE, HSV and few others). Would you mind attaching your augmentation pipeline to this ticket?
