### ISSUE TITLE
Error while installing imaug due to Shapely package

### ISSUE THREAD

**Issue by adizhol** [albu/albumentations#155]
## 🐛 Installation error
```
Collecting Shapely (from imgaug)
  Using cached https://files.pythonhosted.org/packages/a2/fb/7a7af9ef7a35d16fa23b127abee272cfc483ca89029b73e92e93cdf36e6b/Shapely-1.6.4.post2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-kdsk2c_6\Shapely\setup.py", line 80, in <module>
        from shapely._buildcfg import geos_version_string, geos_version, \
      File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-kdsk2c_6\Shapely\shapely\_buildcfg.py", line 200, in <module>
        lgeos = CDLL("geos_c.dll")
      File "C:\ProgramData\Anaconda3\envs\pytorch04_py36\lib\ctypes\__init__.py", line 348, in __init__
        self._handle = _dlopen(self._name, mode)
    OSError: [WinError 126] The specified module could not be found
```

Windows Server 2016
python 3.6.6
albumentations version 0.1.8

pip install imgaug
(or pip install albumentations )

The error is probably due to missing C compiler required for building the dll.
Workaround: 

1. install binaries from https://www.lfd.uci.edu/~gohlke/pythonlibs/#shapely
2. conda install shapely
   pip install imgaug
 

ref: https://gis.stackexchange.com/questions/62925/why-is-shapely-not-installing-correctly

**Comment by albu** [comment]
should be fixed in 0.1.11, please reopen if you are still issuing this

**Comment by ErestorX** [comment]
I got the same issue installing imgaug, @adizhol solution worked well.

**Comment by ThomVett** [comment]
Also solved it by direclty installing shapely from conda, without having to install any binaries beforehand.

Windows 10, Python 3.6.8

**Comment by Anand-Solanki** [comment]
I was facing a similar issue.

Workaround provided by adizhol worked for me as well. 

Thank you!

**Comment by etatbak** [comment]
conda install shapely
pip install imgaug
these solved my problem, thanks

**Comment by jacentyj** [comment]
(base) C:\WINDOWS\system32>pip install shapely
Collecting shapely
  Using cached https://files.pythonhosted.org/packages/a2/fb/7a7af9ef7a35d16fa23b127abee272cfc483ca89029b73e92e93cdf36e6b/Shapely-1.6.4.post2.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):

(base) C:\WINDOWS\system32>conda install shapely
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - shapely

Current channels:

  - https://conda.anaconda.org/r/win-64
  - https://conda.anaconda.org/r/noarch
  - https://conda.anaconda.org/conda/win-64
  - https://conda.anaconda.org/conda/noarch

Could anybody help? I used to install only using pip

**Comment by VasilijKolomiets** [comment]
Lot of thanks!
But in Anaconda it need to be done in new created environment even if in base  environment I did it.
All works!

**Comment by AkshatRepo** [comment]
The complete process to install shapely is described in this article which works perfectly fine and this article will clear your related error as well. The link of that article is
<a href="https://www.akshatvasistha.com/2019/10/how-do-real-time-image-segmentation-mask-rcnn.html"> Real-time image segmentation with MaskRCNN </a>
