### ISSUE TITLE
pip install albumentations is failed with error code 1

### ISSUE THREAD

**Issue by Deeperss** [albu/albumentations#163]
## 🐛 Bug

When I  install the albumentations on windows7 for keras, the bug is jump on face.

## Environment

 - Albumentations version (e.g., 0.1.10):
 - Python version (e.g., 3.5):
 - OS (e.g., windows7):
 - How you installed albumentations (conda, `pip`, source):

## Additional context

 (keras) $ pip install imgaug
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting imgaug
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/af/fc/c56a7da8c23122b7c5325b941850013880a7a93c21dc95e2b1ecd4750108/imgaug-0.2.7-py3-
none-any.whl (644kB)
    100% |████████████████████████████████| 645kB 2.9MB/s
Requirement already satisfied: Pillow in d:\software\anaconda3\envs\keras\lib\site-packages (from imgaug) (5.4.1)
Requirement already satisfied: imageio in d:\software\anaconda3\envs\keras\lib\site-packages (from imgaug) (2.4.1)
Requirement already satisfied: numpy>=1.7.0 in d:\software\anaconda3\envs\keras\lib\site-packages (from imgaug) (1.15.4)
Requirement already satisfied: scikit-image>=0.11.0 in d:\software\anaconda3\envs\keras\lib\site-packages (from imgaug) (0.14.1)
Collecting Shapely (from imgaug)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/a2/fb/7a7af9ef7a35d16fa23b127abee272cfc483ca89029b73e92e93cdf36e6b/Shapely-1.6.4.pos
t2.tar.gz (225kB)
    100% |████████████████████████████████| 235kB 6.4MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\WangZhao\AppData\Local\Temp\pip-install-h64vi3v5\Shapely\setup.py", line 80, in <module>
        from shapely._buildcfg import geos_version_string, geos_version, \
      File "C:\Users\WangZhao\AppData\Local\Temp\pip-install-h64vi3v5\Shapely\shapely\_buildcfg.py", line 200, in <module>
        lgeos = CDLL("geos_c.dll")
      File "D:\Software\Anaconda3\envs\keras\lib\ctypes\__init__.py", line 348, in __init__
        self._handle = _dlopen(self._name, mode)
    OSError: [WinError 126] 找不到指定的模块。

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\WangZhao\AppData\Local\Temp\pip-install-h64vi3v5\Shapely\

**Comment by albu** [comment]
should be fixed in 0.1.11, please reopen if you are still issuing this

**Comment by Deeperss** [comment]
> should be fixed in 0.1.11, please reopen if you are still issuing this

Thank you ,this issus is disappeared.
