### ISSUE TITLE
How to qucikly generate image in one batch?

### ISSUE THREAD

**Issue by Deeperss** [albu/albumentations#164]
## 📚 Documentation

Thanks for you work, I have other question, how to use your Albumentations to make one image generate more different photos from each other in one batch?

**Comment by BloodAxe** [comment]
Perhaps, something like this can do the work:
```
x = { 'image': ..., 'mask': ... }
aug = A.Compose([...])
batch = default_collate([aug(**x) for x in repeat(x, batch_size)`])
```
A `default_collate` is a util function from Pytorch, that is default collate function used by DataLoader for assembling a batch from individual samples.
