### ISSUE TITLE
Can't iterate over transformation output

### ISSUE THREAD

**Issue by Sphinxs** [albu/albumentations#169]
I'm using PyTorch to augment a [dataset](http://www.robots.ox.ac.uk/~vgg/data/flowers/102/). I have downloaded the dataset and loaded it using the `torchvision.datasets.ImageFolder` 'n `torch.utils.data.DataLoader` functions. If I use a transformation from PyTorch the data is loaded, transformed and plotted without any errors, but if I apply some transformation from Albumentation I receive the following error:

```shell
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-15-6a0e45004b2c> in <module>
      4 for item in train_vectors:
      5     # Get epoch
----> 6     images, labels = iter(item['data']).next()
      7 
      8     # Plot images

TypeError: Traceback (most recent call last):
  File "/home/pc/.pyenv/versions/anaconda3-2018.12/envs/vida/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/pc/.pyenv/versions/anaconda3-2018.12/envs/vida/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/pc/.pyenv/versions/anaconda3-2018.12/envs/vida/lib/python3.6/site-packages/torchvision/datasets/folder.py", line 103, in __getitem__
    sample = self.transform(sample)
  File "/home/pc/.pyenv/versions/anaconda3-2018.12/envs/vida/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 49, in __call__
    img = t(img)
TypeError: __call__() takes 1 positional argument but 2 were given
```

or 

```shell
tensor is not a torch image
```

The transformation list:

```python
transform_train = [
    albumentations.augmentations.transforms.JpegCompression(),
    torchvision.transforms.Resize((height, width)),
    torchvision.transforms.ToTensor(),
    torchvision.transforms.Normalize(mean=(0,485, 0,456, 0,406), std=(0,229, 0,224, 0,225))
]
```

The loading:

```python
torch.utils.data.DataLoader(
    dataset=torchvision.datasets.ImageFolder(
        root=path,
        transform=transform
    ),
    batch_size=batch,
    shuffle=shuffle,
    num_workers=workers        
)
```

The iteration:

```python
for item in train_vectors:
    # Get epoch
    images, labels = iter(item['data']).next()
```

I'm using PyTorch 0.4.1, Albumentations 0.1.11 and Img Aug 0.2.7 (I'm running the notebooks inside a virtual environment created based on a virtual image installed using Pyenv).

I researched, but I couldn't figure out why I'm receiving this error, I have tried to iterate using enumerate, range and so on and nothing works, the complete code and references can be found [here](https://github.com/Sphinxs/Vida/blob/master/notebooks/vida.ipynb).

Do I need to iterate over the dataset of a different way or convert the data to another format... ?

**Comment by BloodAxe** [comment]
Hi. I'm not sure whether Albumentations is compatible with a `torchvision.datasets.ImageFolder`. 
I personally use my own dataset classes where transformations and image to tensor conversion already baked in.  Torchvision's transformation API is quite different to ours and I don't see an easy way to glue them together.

**Comment by Sphinxs** [comment]
Hi, @BloodAxe. I had also tried to use the PIL and Tensor image (iterating over each dataset and not using the `ImageFolder`), but I have received an error (invalid type) when I was training the Network.

The` ImageFolder` and the `DataLoader` APIs are very bad, the preprocessing had taken a huge amount of time (to do simple things, I had need to read the code of the methods). I have finished the work in question, but I'm going to use another framework to try data augmentation, synthetic data, etc. The PyTorch documentation sucks.

Thanks for the answer, I really appreciate that.

**Comment by mostafaelaraby** [comment]
if you want to use albumentations with torchvisions without creating a custom dataloader
that's what i did and passed it to torchvision dataloader and it worked
`def get_training_augmentation():
    train_transform = [
        albu.Resize(32 , 32)
    ]
    transforms =  albu.Compose(train_transform)
    return lambda img:transforms(image=np.array(img))`
