### ISSUE TITLE
`SmallestMaxSize` (and `LongestMaxSize`?) introduce new label IDs in transformed masks

### ISSUE THREAD

**Issue by marcocaccin** [albu/albumentations#175]
## 🐛 Bug

As the title says, new IDs appear when these functions are applied to multi-label masks. 
I only observed this issue very rarely, but:
- should not be there at all, and may be happening more often than we can detect it
- it messes up model training/inference pipelines by introducing non-existent classes.

This behaviour should **not** be happening because `DualTransform` explicitly [transforms masks with `cv2.INTER_NEAREST` interpolation](https://github.com/albu/albumentations/blob/594274b645f21e9899a0c40d6727a79555973509/albumentations/core/transforms_interface.py#L119), but that piece of code is somehow bypassed.

 ## To Reproduce

```
import os
import albumentations
import cv2
import numpy as np
from albumentations.augmentations import functional as F

os.system('wget https://www.dropbox.com/s/q6v1egasojxazkz/fail_mask_example.png')

m0 = cv2.imread('fail_mask_example.png', 0)
dummy_img = np.zeros(m0.shape + (3,), dtype=np.uint8)
print(m0.shape)
# >>> (2448, 3264)
print(np.unique(m0))
# >>> [0, 1, 2, 3, 9]

aug0 = albumentations.LongestMaxSize()
m1 = aug0(image=dummy_img, mask=m0)['mask']
print(np.unique(m1))
# >>> [0, 1, 2, 3]  # This is ok, a tiny label vanished when scaling down

aug1 = albumentations.SmallestMaxSize()
m2 = aug1(image=dummy_img, mask=m0)['mask']
print(np.unique(m2))
# >>> [0, 1, 2, 3, 6]  # BAD, a new label appeared out of nowhere

# This also happens with 2 mask values only
mask_nines = ((m0 == 9) * 9).astype(np.uint8)
print(np.unique(m0))
# >>> [0, 9]
m3 = aug1(image=dummy_img, mask=mask_nines)['mask'] 
print(np.unique(m3))
# >>> [0, 6]

# Now let's try to rewrite SmallestMaxSize by specifying the mask interpolation

class SmallestMaxSizeTry(albumentations.DualTransform):
    def __init__(self, max_size=1024, interpolation=cv2.INTER_LINEAR, always_apply=False, p=1):
        super().__init__(always_apply, p)
        self.inteprolation = interpolation
        self.max_size = max_size

    def apply(self, img, interpolation=cv2.INTER_LINEAR, **params):
        return F.smallest_max_size(img, max_size=self.max_size, interpolation=interpolation)

    def apply_to_mask(self, img, interpolation=None, **params):
        return F.smallest_max_size(img, max_size=self.max_size, interpolation=0)  # MANUALLY EDIT INTERPOLATION HERE

aug_workaround = SmallestMaxSizeTry()
m4 = aug_workaround(image=dummy_img, mask=m0)['mask']
print(np.unique(m4))
# >>> [0, 1, 2, 3, 9]  # It works, no idea what the difference should be :-(
```

## Expected behavior

Not have random classes appearing out of nowhere

## Environment

 - Albumentations version (e.g., 0.1.8): 0.1.8, 0.1.11
 - Python version (e.g., 3.7): 3.5, 3.6
 - OS (e.g., Linux): Ubuntu 16.04
 - How you installed albumentations (`conda`, `pip`, source): pip
 - Any other relevant information:

## Additional context

Don't know if it helps, but class 9 in the example above is very tiny, probably 1 pixel wide.

**Comment by BloodAxe** [comment]
Thanks. It should be fixed #176.
