### ISSUE TITLE
The output shape of `smallest_max_size` is smaller than the speficified size

### ISSUE THREAD

**Issue by fujibo** [albu/albumentations#207]
## 🐛 Bug

The output shape of `smallest_max_size` is smaller than the speficified size.

## To Reproduce
```
from albumentations.augmentations import functional as F
import cv2
import numpy as np

img = np.empty((330, 49), dtype=np.uint8)
out = F.smallest_max_size(img, 256, interpolation=cv2.INTER_LINEAR)
print(out.shape) # (1724, 255)
```

## Expected behavior

The output shape should be `(1724, 256)`.

## Environment

 - Albumentations version: 0.1.12:
 - Python version: 3.7.2:
 - OS: Linux
 - How you installed albumentations (`conda`, `pip`, source): pip

## Additional context
This problem happens because `int(256 / float(49) * 49) = 255`, not equal to `256`.
https://github.com/albu/albumentations/blob/master/albumentations/augmentations/functional.py#L357

**Comment by ternaus** [comment]
Fixed in https://github.com/albu/albumentations/pull/209
