### ISSUE TITLE
GaussNoise does not work correctly on small images

### ISSUE THREAD

**Issue by Maxfashko** [albu/albumentations#213]
## 🐛 Bug

Hi Vladimir!

The error lies in the fact that the GaussNoise method does not work correctly on small pictures (i tested 128*64), since the argument `var` requires an integer value:  `GaussNoise(var_limit=(1, 1), always_apply=False, p=1)`

https://files.slack.com/files-pri/T040HKJE3-FGMFW433R/image.png

It helped for me:

```
def add_gaussian_noise(image_in, noise_sigma):
    temp_image = np.float64(np.copy(image_in))

    h = temp_image.shape[0]
    w = temp_image.shape[1]
    noise = np.random.randn(h, w) * noise_sigma

    noisy_image = np.zeros(temp_image.shape, np.float64)
    if len(temp_image.shape) == 2:
        noisy_image = temp_image + noise
    else:
        noisy_image[:,:,0] = temp_image[:,:,0] + noise
        noisy_image[:,:,1] = temp_image[:,:,1] + noise
        noisy_image[:,:,2] = temp_image[:,:,2] + noise

    return noisy_image
```

**Comment by albu** [comment]
looks like it does not work for float32 but works correctly for uint8
