### ISSUE TITLE
Error in returning invisible keypoints

### ISSUE THREAD

**Issue by cdicle** [albu/albumentations#215]
## 🐛 Bug

One can return invisible keypoints by setting `remove_invisible` flag to `False` as follows
```
augmentor = albu.Compose([...], keypoint_params={'format': 'xy', 'remove_invisible': False})
```
However, due to this [check](https://github.com/albu/albumentations/blob/master/albumentations/core/composition.py#L216), those invisible keypoints result in an error. Note that, `check_validity` flag which supposed to be conditioned on `remove_invisible` flag is always `True`.

Will submit a fix following up this bug report.
Best.

**Comment by BloodAxe** [comment]
Merged. Thanks for the PR!
