### ISSUE TITLE
Is there a non-random ShiftScaleRotate?

### ISSUE THREAD

**Issue by darugar** [albu/albumentations#230]
## 📚 Documentation

I need to ShiftScaleRotate images by specific amounts instead of by random amounts. Is this possible or do I need to apply the non-random shift, scale, and rotate operations separately?

How would you feel about an API where each operation takes a *random* flag to specify whether it should be applied randomly or deterministically? That way there'd be less API functions, and one wouldn't have to guess which functions are random and which deterministic.

**Comment by albu** [comment]
https://github.com/albu/albumentations/blob/master/albumentations/augmentations/transforms.py#L412 you can pass 
```shift_limit=(0.0625, 0.0625), scale_limit=(0.1, 0.1), rotate_limit=(45, 45)``` and it will be applied deterministically
