### ISSUE TITLE
some question about OneOf block and GaussianNoise

### ISSUE THREAD

**Issue by woaichipinngguo** [albu/albumentations#232]
## 📚 Documentation

what is the function of OneOf block?  
And what is the relationship between between IAAAdditiveGaussianNoise and GaussianNoise?

![a](https://user-images.githubusercontent.com/15664013/54082287-d238ee80-434d-11e9-96f2-672f2f7a5b49.JPG)

**Comment by albu** [comment]
https://albumentations.readthedocs.io/en/latest/probabilities.html#oneof-block
transforms with IAA prefix are from imgaug library, some of them are here only for consistency.
