### ISSUE TITLE
Multitask augmentation

### ISSUE THREAD

**Issue by E1eMenta** [albu/albumentations#237]
Python 3.6
Albumentations 0.2.0

```
import numpy as np
from albumentations import Compose, VerticalFlip

additional_targets = {"image1": "image", "image2": "image", "bboxes1":"bboxes", "bboxes2":"bboxes"}
transform = Compose([VerticalFlip(p=1.0),],
        bbox_params={'format': 'pascal_voc', 'min_area': 0, 'min_visibility': 0.3, 'label_fields': []},
        additional_targets=additional_targets
    )

image = np.zeros((300, 300, 3), dtype=np.float32)
bboxes = np.array([[100, 100, 200, 200], [10, 30, 20, 70]], dtype=np.float32)


sample = {
    "image":image.copy(), "bboxes":bboxes.copy(),
    "image1":image.copy(), "bboxes1":bboxes.copy(),
    "image2":image.copy(), "bboxes2":bboxes.copy()
}

out = transform(**sample)
```

While Flipping "bboxes" converts from pascal format to albu internal format, but  "bboxes1" and  "bboxes2" are not converted.
What am I doing wrong?

**Comment by albu** [comment]
looks like bboxes are not supported as additional targets, thanks for bugreport

**Comment by albu** [comment]
Just in case - what is your usecase? why do you need multiple bboxes arrays?

**Comment by E1eMenta** [comment]
Video object detection. Augmentation of the whole video simultaneously.

**Comment by E1eMenta** [comment]
I achived the aim by using same seed(for numpy.random and random) for images in one video and another seed for other video.
