### ISSUE TITLE
ToTensor() doesn't transform additional targets

### ISSUE THREAD

**Issue by velikodniy** [albu/albumentations#243]
## To Reproduce

```python
aug = albumentations.Compose(
    [albumentations.pytorch.ToTensor()],
    additional_targets={'image2': 'image'}
)

out = aug(image=image, image2=image)
```

## Expected behavior

I expected types of `image` and `image2` to be `torch.Tensor`, but `ToTensor()` was applied only to `image` target (this behaviour is hard coded as far as I understand).

```python
type(out['image']), type(out['image2'])
```
returns
```
(torch.Tensor, numpy.ndarray)
```

## Environment

 - Albumentations version: 0.2.2
 - Python version: 3.7.2
 - OS: Ubuntu 18.04
 - How you installed albumentations (`conda`, `pip`, source): pip
 - Any other relevant information: —

## Additional context

—

**Comment by ternaus** [comment]
Fixed in https://github.com/albu/albumentations/pull/246
