### ISSUE TITLE
Augmentation per image applied to multiple bboxes but not to masks

### ISSUE THREAD

**Issue by Paperone80** [albu/albumentations#247]
## 🐛 Bug

Hi, 
When the input data dict is like this:
```
def aug_test(p=1., bbox_format='pascal_voc', min_area=0., min_visibility=0.):
    return Compose(
        [
            (VerticalFlip(p=0.))
            , (RandomRotate90(p=1))
        ]
        , bbox_params={'format': bbox_format, 
                       'min_area': min_area, 
                       'min_visibility': min_visibility, 
                       'label_fields': ['category_id']
                      }
        , p=p)

data = {'image': image
        , 'bboxes': [[bbox_1], bbox_2]
        , 'category_id': annotations['category_id']
        , 'mask': mask_1

augmentation = aug_test(p=1)
augmented = augmentation(**data)
```
The 2 bboxes are transformed correctly and the one mask as well. 

However, if the data is changed to reflect the corresponding masks to the bboxes then augmentation fails or returns meshed up arrays.
```
data = {'image': image
        , 'bboxes': [[bbox_1], bbox_2]
        , 'category_id': annotations['category_id']
        , 'mask': [mask_1, mask_2]  
}
```
Sometimes the returned  looks like this:
```
augmented['mask'].shape=(height, 2, width). 
```

## Expected behavior
Expected would be that augmentation is applied to each mask separately and returned like 'bboxes', e.g. 
```
augmented['mask'][0].shape=(height, width)
augmented['mask'][1].shape=(height, width)
```
## Why is this important?
The expected behaviour reflects the way how data is stored in tf.record for example to save space:
```
[...]
'image/encoded': bytes_feature(encoded_jpg)
'image/object/bbox/xmin': bytes_list_feature([])
 'image/object/bbox/xmax': bytes_list_feature([])
 'image/object/bbox/ymin': bytes_list_feature([])
 'image/object/bbox/ymax': bytes_list_feature([])
'image/object/mask': bytes_list_feature([])
[...]
```
Alternative would be to augment 1 image, 1 bbox and 1 mask together at a time and store which uses more space than necessary because you often have multiple bboxes/masks per image, imho.  

Maybe worth a fix. Maybe there is another way around it I have not seen yet because I just started playing with the library (which is awesome, btw) since yesterday. Thanks.

## Environment

 - Albumentations version (e.g., 0.2.2): 0.2.2
 - Python version (e.g., 3.5): 3.5
 - OS (e.g., Linux): Red Hat 7.4
 - How you installed albumentations (`conda`, `pip`, source): pip 
 - Any other relevant information: n/a

**Comment by Paperone80** [comment]
@ternaus, has the issue been fixed or is it not of a priority right now? Thanks.

**Comment by davodogster** [comment]
@ternaus Has this been fixed? I have coco json polygon annotations and I want to crop them (image, bbox, and mask) then write the new cropped coco_json files.

**Comment by Dipet** [comment]
Masks are the images, so they are must have the shape `[height, width, channels]` and must be `numpy.ndarray`
The author of the issue provided mask in the wrong format, as I understand in the format `[channels, height, width]`
