### ISSUE TITLE
Is there a way to provide bounding box that is in YOLO format?

### ISSUE THREAD

**Issue by LywuPy** [albu/albumentations#248]
Theres only Pascal_VOC or COCO bounding box format as far as i know. However I need a way to provide bounding box in YOLO format

**Comment by BloodAxe** [comment]
You can either convert bboxes from YOLO format to COCO or VOC before sending to pipeline, or attach YOLO keypoints format reference here and wait until it's support will be added to the library.

**Comment by Paperone80** [comment]
@LywuPy Check out: [Imantics](https://github.com/jsbroks/imantics ).

**Comment by Dipet** [comment]
YOLO format support added #334
