### ISSUE TITLE
Feature request Support cutout augmentation

### ISSUE THREAD

**Issue by newebug** [albu/albumentations#25]
Can you please add support of Cutout augmentation, that will be very useful.

**Comment by ternaus** [comment]
Added.

https://github.com/albu/albumentations/commit/5af82d309748dfca248129be31a54bb5b0ede3e9

**Comment by newebug** [comment]
Good job! And RandomErase ?

**Comment by ternaus** [comment]
It looks like a cutout, but with one hole.

**Comment by newebug** [comment]
Yeah, it add some noise in the hole instead of set to zero
