### ISSUE TITLE
How to implement  augmentation of  multi-binary mask image in the segmentation task

### ISSUE THREAD

**Issue by blakeliu** [albu/albumentations#252]
## 🐛 Bug

Like this : augmented = aug(image=image, mask=[a_mask, b_mask, c_mask]) 
## To Reproduce

1.
1.
1.

## Environment

 - Albumentations version (e.g., 0.1.8): 0.2.2
 - Python version (e.g., 3.7): 3.6.7
 - OS (e.g., Linux):ubuntu 16.4 lts
 - How you installed albumentations (`conda`, `pip`, source):conda
 - Any other relevant information:

**Comment by albu** [comment]
https://github.com/albu/albumentations/blob/master/notebooks/example_multi_target.ipynb like this. please re-open if it's still not clear

**Comment by jaewooklee93** [comment]
@albu That link is now broken, how can I achieve multi-cahnnel mask augmentation?

**Comment by albu** [comment]
https://github.com/albumentations-team/albumentations_examples/blob/master/notebooks/example_multi_target.ipynb
