### ISSUE TITLE
RandomScale function comment section

### ISSUE THREAD

**Issue by Giounona** [albu/albumentations#257]
class RandomScale(DualTransform):
    """Randomly resize the input. Output image size is different from the input image size.
    Args:
        scale_limit ((float, float) or float): scaling factor range. If scale_limit is a single float value, the
            **range will be (1 - scale_limit, 1 + scale_limit).** Default: 0.1.
        interpolation (OpenCV flag): flag that is used to specify the interpolation algorithm. Should 

---------
In the above comment section should not it be 
**range will be (1 + scale_limit, 1 + scale_limit)**
rather than
**range will be (1 - scale_limit, 1 + scale_limit)**
?

because the implementations of versions 0.2.2 and 0.2.3 just add your scale limit to 1.
I had scale limit (0.5 - 1.5) and i ended up scaling everything to (1.5-2.5)
so to make it work properly i had to give as input (-0.5, 0.5)

**Comment by Dipet** [comment]
At last version works properly.
