### ISSUE TITLE
Pytorch error albumentations

### ISSUE THREAD

**Issue by jlevy44** [albu/albumentations#265]
When I pass my numpy array through the transformer:
```
need_to_run = force_apply or random.random() < self.p
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Comment by ternaus** [comment]
Could you please share an example that reproduces the issue?

**Comment by jlevy44** [comment]
I’ve just been reading through the docs. I use torchvision, so I just didn’t realize that you have to specify the arguments to the transformer when you call it, like image=

**Comment by jlevy44** [comment]
And so for segmentation masks you can just add an image2? Is that how it works?

**Comment by albu** [comment]
https://github.com/albu/albumentations#how-to-use

**Comment by jlevy44** [comment]
Got it thanks.

**Comment by jlevy44** [comment]
Nice package! Working now in my pipeline!

**Comment by GadirajuSanjayvarma** [comment]
> I’ve just been reading through the docs. I use torchvision, so I just didn’t realize that you have to specify the arguments to the transformer when you call it, like image=

Can you plz explain it elaborately.I ma also facing the same issue.Force_apply shou;ld be boolean but it is getting PIL image
