### ISSUE TITLE
GaussNoise whitens image and can't accept single value var parameter

### ISSUE THREAD

**Issue by stiansel** [albu/albumentations#268]
## 🐛 Bug
Using the GaussNoise augmenter whitens the input image as it produces only positive values. Additionally it is not possible to specify a single value for the var-parameter as specified in the readme.

## To Reproduce

```

import albumentations
import numpy as np

image_rgb = np.random.randint(0, 256, (32, 32, 3), dtype=np.uint8)

# Issue 1: GaussNoise only produces positive values.
for i in range(10):
    aug = albumentations.GaussNoise(always_apply=True)(image=image_rgb)['image']
    if (aug.astype(np.int16) - image_rgb).min() < 0:
        # The current version never ends up here
        print('At least one pixel was produced with a smaller value than the input image.')
        break
    else:
        print('No negative pixel adjustments made by the noise generator')

# Issue 2: The var parameter does not work if specified as a single value
# The readme for GaussNoise specifies that: "If var_limit is a single float, the range will be (-var_limit, var_limit)"
for i in range(100):
    # This leads to a TypeError: can't convert complex to float
    albumentations.GaussNoise(10.0, always_apply=True)(image=image_rgb)

```

## Expected behavior
For either GaussNoise to produce both positive and negative adjustments, or for the positive-only nature of the class to be included in the documentation.

## Environment

 - Albumentations version (e.g., 0.1.8):  0.2.3
 - Python version (e.g., 3.7):  3.6.8
 - OS (e.g., Linux): Ubuntu 18.04
 - How you installed albumentations (`conda`, `pip`, source): pip

**Comment by ternaus** [comment]
Fixed  in https://github.com/albu/albumentations/pull/270
