### ISSUE TITLE
CoarseDropout fill_value doesn't work

### ISSUE THREAD

**Issue by aeoleader** [albu/albumentations#285]
## 🐛 Bug

Passing different value to CoarseDropout doesn't affect the fill value.

## To Reproduce

```
def strong_aug(p=0.5):
    return Compose([
        RandomRotate90(p=0.8),
        Flip(p=0.7),
        Transpose(p=0.7),
        CoarseDropout(max_holes=3, min_holes=3, fill_value=255, max_width=200, min_width=100, max_height=200, min_height=100, p=1),
        OneOf([
            GridDistortion(distort_limit=0.2, p=1),
            # ElasticTransform(p=1)
        ], p=1.0)
    ], p=p)
```

## Expected behavior

Fill the dropout area by 255 instead of 0.

## Environment

 - Albumentations version (e.g., 0.3.0): 0.3.0
 - Python version (e.g., 3.7): 3.7
 - OS : mac os
 - How you installed albumentations (`conda`, `pip`, source): pip
 - Any other relevant information:

**Comment by bfialkoff** [comment]
Resolved by https://github.com/albu/albumentations/pull/284
