### ISSUE TITLE
No documentation for `keypoint_params` in `Compose` module

### ISSUE THREAD

**Issue by bonlime** [albu/albumentations#289]
## 📚 Documentation

`Compose` modules lacks a description of what `keypoint_params` is. It would be nice to add documentation for it. It should be similar to https://github.com/albu/albumentations/blob/2e25667f8c39eba3e6be0e85719e5156422ee9a9/albumentations/core/composition.py#L110
I thought of making a PR instead of an issue, but I'm don't understand how it really works so it would be nice if one of the maintainers added it.

**Comment by samedii** [comment]
Examples here: https://github.com/albu/albumentations/blob/master/notebooks/example_keypoints.ipynb
although the source code is also using `label_fields`

    Compose(transformations, keypoint_params=dict(format='xy'))(image=image, keypoints=points)
