### ISSUE TITLE
Bug with  masks

### ISSUE THREAD

**Issue by VasLem** [albu/albumentations#290]
## 🐛 Bug

The masks do not follow the rotation of the images

## To Reproduce

1.Define the following transformation:
```
from albumentations import (
    PadIfNeeded,
    HorizontalFlip,
    VerticalFlip,
    CenterCrop,    
    Crop,
    Compose,
    Transpose,
    RandomRotate90,
    ElasticTransform,
    GridDistortion, 
    OpticalDistortion,
    RandomSizedCrop,
    OneOf,
    CLAHE,
    RandomBrightnessContrast,    
    RandomGamma,
    RandomScale,
    LongestMaxSize
)
from albumentations.pytorch.transforms import ToTensor as AlbToTensor

inputs_transformations = Compose([
    RandomScale(scale_limit=0.3, p=0.5),
    LongestMaxSize(256),
    HorizontalFlip(p=0.3),
    VerticalFlip(p=0.3),
    CLAHE(p=0.5),
    RandomBrightnessContrast(p=0.5),    
    RandomGamma(p=0.5),
    AlbToTensor()])
```

I am using kaggle penumonothorax dataset
The result of applying three different transformations to the image and the mask can have the following result:

![image](https://user-images.githubusercontent.com/18720200/60775272-39628600-a129-11e9-9654-96f88e220201.png)

As you can see, the image is horizontally flipped, whereas the mask is vertically filpped.

Version I use is from pip: 0.3.0

The same error can be seen when applying `Flip` transform

**Comment by albu** [comment]
Hi, what is input image shape?

**Comment by VasLem** [comment]
Hey, it is 1024x1024 before the resizing to 256x256

**Comment by albu** [comment]
I mean number of channels. We don't support grayscale (two channels), only 3-channel color images. You can convert it to 3-channel image using opencv or just stack chanels

**Comment by VasLem** [comment]
Sorry for the delay, this was indeed the problem, thank you for your help, closing the issue..

**Comment by pyaf** [comment]
This is a subtle bug, spent an hour figuring it out. There should be a warning for two channel cases.
@albu what do you think?

**Comment by albu** [comment]
yeah, we will consider supporting non-rgb or even add warning to all transforms which does not support grayscale
