### ISSUE TITLE
Adding albumentations to conda-forge

### ISSUE THREAD

**Issue by nrweir** [albu/albumentations#291]
Hi @albu et al.,

I'm a big fan of this project and use it as the primary source of augmentations in our new geospatial ML pipeline, [solaris](https://github.com/cosmiq/solaris). I'm setting up a conda install for solaris, and would like to help add a `conda-forge` feedstock for albumentations to make that possible.

## Justification

I need to get a conda package up for solaris, which necessitates access to all dependencies on the conda cloud. I know from #273 and other previous issues that you have it in a private conda channel, but that makes it hard to use albumentations as a dependency to other conda packages: for example, if I had `solaris` on conda-forge, a downstream user would need to run

```
conda install solaris -c conda-forge -c albumentations
```

I can of course give this instruction for installation, but it complicates things. Furthermore, the conda-forge maintainers frown on using package dependencies outside of `defaults` or `conda-forge` channels, as that channel name would need to be propagated through installs down the dependency tree. For example, if a package uses `solaris` as a dependency, they'd need to do

```conda install [package requiring solaris] -c conda-forge -c albumentations```

...when it becomes increasingly opaque why the albumentations channel is necessary.

## The request

I'd like to help set up a `conda-forge` feedstock for albumentations. Given that you already have the conda build files in the project, this will be very easy. I would also be happy (if desired) to list myself as a maintainer on that conda-forge feedstock to make sure version bumps, etc. go smoothly.

__The advantages of using `conda-forge` instead of a private channel:__

1. Automatic re-builds anytime you update `albumentations` on PyPI so you don't need to update `albumentations` on the conda cloud manually
2. Easier-to-search repository for conda projects, increasing likelihood that `albumentations` will be used by other packages

__Disadvantages:__

1. Some (minimal) maintenance can be required (pretty much just approving pull requests that are automatically triggered by updates to `albumentations`) - I'm happy to help monitor this if desired
2. If you ever add a dependency that isn't available on conda, future versions of the conda install won't work until it's added (though this would be true for any conda channel)

Let me know what you think, and thanks for building a great augmentation pipeline.

**Comment by creafz** [comment]
Hey @nrweir 
Your help with creating and maintaining a conda-forge feedstock would be much appreciated. Do you need any assistance with this task from our side?

**Comment by nrweir** [comment]
@creafz thanks for the response! I don't think I need any help from you all to get it up and running. The only question I have is who I should list as maintainers: along with myself, I assume I should also include @albu, @ternaus, @BloodAxe, and you - let me know if you don't want any of those 5 users listed as maintainers on the conda-forge repo.

**Comment by creafz** [comment]
@nrweir Yes, you are right, those are the correct people to include.

**Comment by nrweir** [comment]
OK great, I'll get that up and running this week.

**Comment by nrweir** [comment]
As I went to create the feedstock, I discovered that another user had created one on June 5: https://github.com/conda-forge/albumentations-feedstock

Looks like this isn't necessary, I'll close.

**Comment by mdraw** [comment]
I'm the creator of the conda-forge feedstock and I just discovered this discussion. I'll add the people listed in https://github.com/albu/albumentations/issues/291#issuecomment-511430166 to the feedstock. If anyone shouldn't be included anymore, please tell me.
