### ISSUE TITLE
Please provide an example for augmentation and classification with pytorch

### ISSUE THREAD

**Issue by dreamflasher** [albu/albumentations#293]
## 📚 Documentation

README.md links to this: https://github.com/albu/albumentations/blob/master/notebooks/example.ipynb – with a title of "classification". But there is no classification inside.

**Comment by ternaus** [comment]
You may try to look at this repo: https://github.com/catalyst-team/classification/blob/master/src/transforms.py#L186

**Comment by dreamflasher** [comment]
I am looking for some best practices for augmentation for classification, shall I go with the `hard_transform` you pointed to? It the readme of albumentations is says that you won several kaggle competitions using the library, what are the typical augmentations you use?

**Comment by albu** [comment]
it 100% depends on task, you just have to run augmentations and see what happens with image

**Comment by dreamflasher** [comment]
Are you taking bets on that? I bet that there are some best practices that are task-independent. But whatever.
