### ISSUE TITLE
Add per-channel compose

### ISSUE THREAD

**Issue by jveitchmichaelis** [albu/albumentations#300]
I've added a new composition function to apply transformations on a per-channel basis. My particular application is to simulate inter-band misalignment in satellite imagery, but I can imagine other uses (for example to simulate fringing/aberration). I initially wrote a transform to do per-channel affine shifts, but it seemed more useful to have a generic composer.

Here's an example of usage:

```
PerChannel([ShiftScaleRotate(shift_limit=0.0125, scale_limit=0.01, rotate_limit=0.1)])
```

And a sample output:

![Lenna](https://i.imgur.com/hxMQeSR.png)

The code is here: https://github.com/jveitchmichaelis/albumentations/blob/6fc672b80393464c9a52c9ba292715e834227e23/albumentations/core/composition.py#L310-L343

I'm keen to have some feedback on a few things:

* I've added some crude detection for mono images, in this case I expand the dimensions to keep the code compact. Is this OK or would a separate case help?
* This works really well with ShiftScaleRotate to add colour fringing, but i'm assuming that this composer should really only use pixel-level transforms because it's not clear how the segmentation map should be modified. `PerChannel` doesn't ever touch segmentation masks/bboxes anyway.
* I've added a couple of basic test cases for mono and multi-channel images. Anything more needed here?
* I'm not too familiar with how transform probabilities are propagated, so it would be good to check if this is OK - e.g. the constructor takes a `p` which I think works as expected. I copied the structure for `OneOf`

Otherwise I think it's good to review: https://github.com/albu/albumentations/pull/301

**Comment by albu** [comment]
Thank you for your contribution. I just wonder if we can somehow split image to multiple images using transformation and then concat channels back.
The reason is that new compose does not work with bounding boxes, keypoints, masks at all

**Comment by jveitchmichaelis** [comment]
WelI would argue it works only with pixelwise transforms in a sensible way. Hence why I only modify the image .

Applying a geometric transform per-channel means that the underlying mask (or bbox or keypoint) no longer makes any sense, unless you choose one channel as a reference and modify the mask based on that one alone. Or, as in my example, you can make small random perturbations to each channel and assume that the original masks etc are still valid.

I'm not sure splitting the image and concating after is an improvement (it's still not clear to me what the geometric labels would transform to), or would you suggest doing e.g. an OR of the transformed masks for each channel?
