### ISSUE TITLE
GaussNoise makes black and white rectanles instead of images.

### ISSUE THREAD

**Issue by MichaelMonashev** [albu/albumentations#306]
## 🐛 Bug

После аугментации часть изображений выглядит как чёрный или белый прямоугольник. Пример: https://prnt.sc/oli43a .

## To Reproduce

Вот такая аугментация даёт проблему:
```
IMG_HEIGHT = 96
IMG_WIDTH = 48

    def aug_train(p=1.0):
        return Compose([
            LongestMaxSize(max_size=max(IMG_HEIGHT, IMG_WIDTH)),
            PadIfNeeded(min_height=IMG_HEIGHT, min_width=IMG_WIDTH),
            GaussNoise(),
            ToGray(p=1.0),
            Cutout(),
        ], p=p)
```

без GaussNoise(), всё работает хорошо.

## Expected behavior

Аугментированные картинки без чёрных и белых прямоугольников.

## Environment

Версию только что обновил через pip3 install -U git+https://github.com/albu/albumentations , но проблема не исчезла.
Python 3.5.3 (default, Sep 27 2018, 17:25:39)
[GCC 6.3.0 20170516] on linux
SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux

**Comment by MichaelMonashev** [comment]
точно такую же проблему вызывает RGBShift() . Пример аугментации, воспроизводящей проблему:
```
IMG_HEIGHT = 96
IMG_WIDTH = 48

    def aug_train(p=1.0):
        return Compose([
            LongestMaxSize(max_size=max(IMG_HEIGHT, IMG_WIDTH)),
            PadIfNeeded(min_height=IMG_HEIGHT, min_width=IMG_WIDTH),
            RGBShift(),
            ChannelDropout(),
            Blur(),
            ToGray(p=1.0),
            Cutout(),
        ], p=p)
```

**Comment by ternaus** [comment]
GaussianNoise добавляет к значениям пикселей и если значения уходят за границы - обрубает на максимальных или минимальных значениях. То есть если у GaussianNoise генерируются большие значения в шуме - будут белые и черные регионы. Предлагается поставить значения для `var_limit` поменьше.

То же самое у RGBShift - надо поставить поменьше значения у `r_shift_limit, g_shift_limit, b_shift_limit`.

Это не избавить от черных и белых регионов, но уменьшит их число.

**Comment by MichaelMonashev** [comment]
Я так понимаю, что ToFloat() перед описанными методами и Normalize() в конце должны решить проблему.
Спасибо!
