### ISSUE TITLE
PadIfNeeded got an unexpected keyword argument 'mask_value'

### ISSUE THREAD

**Issue by wangyunpengbio** [albu/albumentations#321]
## 📚 Documentation

In the documentation, the **PadIfNeeded** has the argument **mask_value**. However, when I use this function, it fails because of no keyword **mask_value**.
**albumentations         0.3.0**
I install from `pip install albumentations`
Isn't this the latest version? Look forward to your reply

**Comment by albu** [comment]
it should work https://github.com/albu/albumentations/blob/master/albumentations/augmentations/transforms.py#L48

**Comment by wangyunpengbio** [comment]
Thanks a lot for your fast reply!!! It works. I reinstall the latest one and the code has been updated.
`pip install -U git+https://github.com/albu/albumentations`
Thanks !!!
