### ISSUE TITLE
Enhancement: Add inverse for geometric transformations

### ISSUE THREAD

**Issue by VasLem** [albu/albumentations#322]
In order to perform comparison between geometrically altered images (eg. TTA), there should be a way to perform the inverse transformation from the one issued on a sample. To accomplish this we need:
- A memory to keep up with what transformations were applied to each image
- An inverse transform for each transformation, or an inverse approximation(eg. for interpolations). If such thing is not implemented or cannot be done, a suitable exception will be raised.

Is this sth that is generally wanted or is it quite an overkill?

**Comment by BloodAxe** [comment]
Definitely an overkill. Also, some transformations are not reversible by definition.
To perform comparison between images, you can store original data and transformed ones and do whatever you want with them.
For TTA you can check https://github.com/BloodAxe/pytorch-toolbelt/blob/develop/tests/test_tta.py

**Comment by VasLem** [comment]
You are right, although the segmentation problems require inverse transformation of the resulting masks, for pixel-pixel comparison... I will try and come back with a pull request if successful

**Comment by BloodAxe** [comment]
Feel free to re-open this issue when you have a proposal draft for the reversal.

**Comment by julienguegan** [comment]
@VasLem Hi ! I am also interested in such inverse transformation (particularly for geometrics) ... Did you finally find a way to do it simply ?

**Comment by Dipet** [comment]
Unfortunately no. For now, we are only focusing on direct transformations.

**Comment by asiron** [comment]
Are there any plans for it ? I am specifically interested in bboxes and keypoints, how can I get a predicted bounding box or keypoint on a transformed image back in the original image's reference frame ? This seems to me like a pretty basic use-case.
