### ISSUE TITLE
image specific parameters, custom transform

### ISSUE THREAD

**Issue by rpgit12** [albu/albumentations#326]
Is it possible to pass parameters along with images into the pipeline? That would allow adjusting the transformations based on specific image properties.

**Comment by albu** [comment]
yes, it's undocumented but you can use it like this: https://github.com/albu/albumentations/blob/master/albumentations/core/transforms_interface.py#L58
override `targets_as_params` to pass params from dict to `get_params_dependent_on_targets` (which is the same as `get_params`.
example: https://github.com/albu/albumentations/blob/master/albumentations/augmentations/transforms.py#L639

**Comment by rpgit12** [comment]
Thanks for your answer. This has worked out perfectly! (I was thinking of extending the pipeline to automatically cache intermediate results but didn't find a good/obvious way to do so. So I'm splitting the pipeline into two portions fow now.)

**Comment by Templarrr** [comment]
@albu Can you please also give an example with fixed commit-hash links? Looks like there were a lot of changes since you've posted above and now links in that comment pointing to something completely different :(

**Comment by Templarrr** [comment]
@rpgit12 or maybe you can help, seems like @albu isn't available.

**Comment by Templarrr** [comment]
@Dipet Thank you!
