### ISSUE TITLE
Unsupported Annontations

### ISSUE THREAD

**Issue by MentalGear** [albu/albumentations#327]
I was a bit surprised that some bounding/mask/annotation data was not supported on filters like "ElasticTransform", since they are available and supported on the imgaug library.
As this library aims to be a wrapper for those augmentation libraries, it would be great if it would also support their annontation spectrum.
`NotImplementedError: Method apply_to_bbox is not implemented in class ElasticTransform`

**Comment by albu** [comment]
It's not strongly a wrapper, only few transforms are wrapped from imgaug. Elastic is not one of them, it's our own optimized version

**Comment by MentalGear** [comment]
OK, is there a possibility to circumvent or tell the library to use the imgaug version instead ?
Would really require annotation support for me project.

**Comment by albu** [comment]
you can write a wrapper around imgaug version or even contribute by adding support of bounding boxes to our elastic transform
