### ISSUE TITLE
probability 1.0 not working

### ISSUE THREAD

**Issue by sonfiree** [albu/albumentations#356]
probability with a value of 1.0 does not always work. There should be a 100% response, but in the next 80%

```
image = cv2.imread(i)
aug = A.Blur(p=1, blur_limit = 9)
image = aug(image=image)['image']
```

Windows 10
albumentations 0.3.3

**Comment by BloodAxe** [comment]
Hi. Can you please clarify what is the meaning of `80% response` in this context? I don't think there is something wrong with probability, perhaps what you want is `A.Blur(p=1, blur_limit = (9,9))`.

**Comment by sonfiree** [comment]
I submit 100 pictures and about 80 of them are blurry

**Comment by Dipet** [comment]
In my case all works.
```
image = np.random.randint(0, 256, (256, 256, 3), dtype=np.uint8)
result = []
aug = Blur(p=1, blur_limit = 9)
for i in tqdm(range(10000)):
    img = aug(image=image)['image']
    result.append(int(np.all(image == img)))
result = np.array(result)
print(result.sum(), len(result))
```

How you check that images are not blurry?

**Comment by sonfiree** [comment]
It`s work `A.Blur(p=1, blur_limit = (9,9))`.


Correct a document?

> `class albumentations.augmentations.transforms.Blur(blur_limit=7, always_apply=False, p=0.5)`
> `blur_limit = (?,?)`
