### ISSUE TITLE
ToTensorV2 does not use additional targets

### ISSUE THREAD

**Issue by albu** [albu/albumentations#357]
We also want to apply ToTensorV2 to additional targets but it haven't been done in initial PR

**Comment by vfdev-5** [comment]
Should not this test : https://github.com/albu/albumentations/blob/8ba400e3f048b5f596670046e25ed90650065f8d/tests/test_pytorch.py#L19
 fail if `ToTensorV2` would not be applied to additional targets or am I missing something ?

**Comment by albu** [comment]
sorry, seems like I was sleepy
