### ISSUE TITLE
RandomFog and other augmentations can get stuck in infinite while loops

### ISSUE THREAD

**Issue by nsfabina** [albu/albumentations#361]
## 🐛 Bug

RandomFog (and other augmentations with while loops) may get stuck in infinite while loops under certain conditions. At least one of those conditions is when an image has been augmented prior to RandomFog being applied.

## To Reproduce

I was able to get this bug with an image using the following compose operation:
```
    return albumentations.Compose([
        albumentations.RGBShift(r_shift_limit=0.2, g_shift_limit=0.2, b_shift_limit=0.2, p=1),
        albumentations.RandomFog(fog_coef_lower=0, fog_coef_upper=1, alpha_coef=0.08, p=1),
    ])
```
After ~2 mins of waiting, I interrupted and the code was still here
```
~/miniconda3/envs/asu/lib/python3.7/site-packages/albumentations/augmentations/transforms.py in get_params_dependent_on_targets(self, params)
   1609
   1610         while midx > -hw or midy > - hw:
-> 1611             for i in range(hw // 10 * index):
   1612                 x = random.randint(midx, width - midx - hw)
   1613                 y = random.randint(midy, height - midy - hw)
```

## Expected behavior

A few thoughts after testing the library:
- many augmentations appear to be order-of-operations dependent, might be worth putting a note in the documentation about how results can vary drastically depending on this order
- specifically for RandomFog and other augmentations where results depend on the image properties, perhaps a warning that they should be applied first, or perhaps a warning that they can have suboptimal interactions with other augmentations
- augmentations with while loops may need some sort of time- or iteration-based limit to avoid hangs or excessive pre-processing
- (that's all I've got, sorry, it's still early here!)

## Environment

 - Albumentations version (e.g., 0.1.8):  albumentations==0.3.3
 - Python version (e.g., 3.7):  3.7
 - OS (e.g., Linux):  OSX
 - How you installed albumentations (`conda`, `pip`, source): conda
 - Any other relevant information: nope

**Comment by nsfabina** [comment]
Apologies. Further testing shows that I'm able to do this with RandomFog only, that there's no interactive effect here.

Reproduce:
```
    return albumentations.Compose([
        albumentations.RandomFog(fog_coef_lower=0, fog_coef_upper=1, alpha_coef=0.08, p=0.5),
    ])
```

**Comment by ternaus** [comment]
Fixed in https://github.com/albu/albumentations/pull/362

**Comment by opeide** [comment]
I still had this issue with randomfog in albumentations 1.1.0, with arguments lower 0, upper 0.2 and alpha 0.5.
