### ISSUE TITLE
Contributions not possible without forking

### ISSUE THREAD

**Issue by nsfabina** [albu/albumentations#363]
## 🐛 Bug

Contributions are not possible without forking.

Project needs to have permissions updated or documentation modified to explain fork -> modify -> PR process.

**Comment by ternaus** [comment]
I believe `fork -> modify -> PR` is a standard process for contributing to open-source projects.

Which part is confusing?

**Comment by nsfabina** [comment]
From the documentation, contribution instructions are:

> Clone the repository:
> `git clone git@github.com:albu/albumentations.git`

So, updating that portion of the documentation to make it clear that you want users to fork and then submit PRs.

**Comment by ternaus** [comment]
Fixed in https://github.com/albu/albumentations/pull/366
