### ISSUE TITLE
caching

### ISSUE THREAD

**Issue by rpgit12** [albu/albumentations#390]
It'd be nice if some sort of cache element could be inserted that automatically caches images after a certain step in the pipeline, and skips preceding portions if a cached image exists. I think that would fit neatly into how pipelines are set up.

I use two separate pipelines which arguably works fine too.

**Comment by ternaus** [comment]
What is the use case?

For images that are not too large, it would not create a big advantage.

**Comment by Dipet** [comment]
It is assumed that we use random transforms with a lot of random images, so we we do not need cache this images, because on every call we get different image. Also cache does not work well with multiprocessing.
If you need cache images, you can cache it in your dataset.

**Comment by rpgit12** [comment]
Sorry for following up late - I added custom transforms that take a lot of time hence caching made sense. That said I understand this isn't the main objective of the library.
