### ISSUE TITLE
Need fix keypoints changes 

### ISSUE THREAD

**Issue by Dipet** [albu/albumentations#394]
Need change angle
- [ ] VerticalFlip
- [ ] HorizontalFlip
- [ ] Flip

Current  version:
```
def keypoint_vflip(kp, rows, cols):
    """Flip a keypoint vertically around the x-axis."""
    x, y, angle, scale = kp
    c = math.cos(angle)
    s = math.sin(angle)
    angle = math.atan2(-s, c)
    return [x, (rows - 1) - y, angle, scale]
```

**Comment by Dipet** [comment]
Current version of this transforms does not change keypoints angle.
Example how it is implements you can look at `Transpose` transform.

**Related files**
* `albumentations/augmentations/transforms.py`
* `albumentations/augmentations/functional.py`

**Comment by Arquestro** [comment]
And is there a unit test for checking flip angles?

**Comment by Dipet** [comment]
OMG, it is really my fail. I did not read this code carefully. The code is right, but a little bit overcomplicated

**Comment by Arquestro** [comment]
Maybe i'm wrong, but if you look closely at
```
angle = math.atan2(-s, c)
angle = math.atan2(s, -c)
```
will result in the same angle with up to `2*pi`
There will be not horizontal flip in horizontal, but vertical, imho
