### ISSUE TITLE
How to make identical composed random/elastic transforms on  image pair(input,target) for segmentation?

### ISSUE THREAD

**Issue by AlexLuya** [albu/albumentations#397]
Hello,in segmentation task,identical spatial transforming result are expected on image pair (input,target),even for random(crop/rotation) or elastic transforms.Google tells to set random seed,so I did it like this:
```
        # ensure same randomness on both image and mask
        seed = np.random.randint(2147483647)
        random.seed(seed) 

       spatialTransforms=Compose(ElasticTransform(),RandomCrop()....)
        
        # read images
        image = imread(..)
        mask = imread(...)
        
        # apply spatial transforms on both image and mask
         transformedImage = spatialTransforms(image = image)
         transformedMask = spatialTransforms(image = mask) 
```
but doesn't worked as expected,so how to do it right?

**Comment by albu** [comment]
https://github.com/albu/albumentations#how-to-use

**Comment by ternaus** [comment]
@AlexLuya 


```
transformed = SpatialTransforms(image=image, mask=mask)

image = transformed['image']
mask = transformed['mask']
```
will do the job. We already took care of all random seeds that are involved.

As @albu pointed out, it may help to check examples in notebooks.

**Comment by AlexLuya** [comment]
@ternaus
Thanks,how to handle three images case,such as unet which has a triplet (image,mask,weight,map) need to be performed identical spatial transformation.

**Comment by ternaus** [comment]
https://github.com/albu/albumentations/blob/master/notebooks/example_multi_target.ipynb covers this use case.
