### ISSUE TITLE
ImportError: libXrender.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by mobassir94** [albu/albumentations#415]
I tried both **pip install -U git+https://github.com/albu/albumentations** and **pip install albumentations** in paperspace but while importing the library i get this error : 

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-18-4a5d86dffb20> in <module>
     67 
     68 #from albumentations import (HorizontalFlip,VerticalFlip,Cutout,SmallestMaxSize,ToGray,CenterCrop, ShiftScaleRotate,RandomBrightnessContrast, Blur,Normalize, Resize, Compose, GaussNoise)
---> 69 from albumentations.pytorch import ToTensor
     70 
     71 warnings.filterwarnings("ignore")

/usr/local/lib/python3.6/dist-packages/albumentations/__init__.py in <module>
      3 __version__ = '0.3.3'
      4 
----> 5 from .core.composition import *
      6 from .core.transforms_interface import *
      7 from .core.serialization import *

/usr/local/lib/python3.6/dist-packages/albumentations/core/composition.py in <module>
      8 from albumentations.core.serialization import SerializableMeta
      9 from albumentations.core.six import add_metaclass
---> 10 from albumentations.core.transforms_interface import DualTransform
     11 from albumentations.core.utils import format_args, Params
     12 from albumentations.augmentations.bbox_utils import BboxProcessor

/usr/local/lib/python3.6/dist-packages/albumentations/core/transforms_interface.py in <module>
      3 import random
      4 
----> 5 import cv2
      6 
      7 from albumentations.core.serialization import SerializableMeta

/usr/local/lib/python3.6/dist-packages/cv2/__init__.py in <module>
      1 import importlib
      2 
----> 3 from .cv2 import *
      4 from .data import *
      5 

ImportError: libXrender.so.1: cannot open shared object file: No such file or directory

**Comment by Dipet** [comment]
Maybe in your system does not installed libXrender. Try install it.
`sudo apt-get install libfontconfig1 libxrender1`

**Comment by mobassir94** [comment]
i don't find any sudo installing option in paperspace,i am running jupyter notebook and i can do pip install commands there.any help please? @Dipet

**Comment by Dipet** [comment]
You may try write `!sudo apt-get install libxrender1` from jupyter.

**Comment by mobassir94** [comment]
i have solved my problem,thanks @Dipet 
i found terminal option in homepage
