### ISSUE TITLE
Unexpected behavior of `max_holes` in CoarseDropout

### ISSUE THREAD

**Issue by t-hanya** [albu/albumentations#436]
## 🐛 Bug

CoarseDropout may produce `max_holes + 1` holes. 

## To Reproduce

<img width="932" alt="スクリーンショット 2019-10-21 21 00 58" src="https://user-images.githubusercontent.com/18238865/67203592-73406980-f446-11e9-865c-88337a34899c.png">

In CoarseDropout code, the number of holes is determined by `random.randint(self.min_holes, self.max_holes + 1)`, but `random.randint(a, b)` function returns random integer in range[a, b], including both end points.

```python
>>> import random
>>> for _ in range(10):
...     print(random.randint(0, 1))
... 
0
0
0
0
0
1
0
1
0
1
>>> 
```

## Expected behavior

For option name `max_holes`, we expect CoarseDropout function produces at most `max_holes` holes.

## Environment

 - Albumentations version (e.g., 0.1.8): 0.4.1
 - Python version (e.g., 3.7): 3.6.5
 - OS (e.g., Linux): macOS
 - How you installed albumentations (`conda`, `pip`, source): pip

**Comment by ternaus** [comment]
Fixed
