### ISSUE TITLE
some boxes can’t transfer correctly

### ISSUE THREAD

**Issue by GYxiaOH** [albu/albumentations#457]
## 🐛 Bug

for example: i have a bbox,[152.  35.] [205.  17.] [208.  26.] [155.  43.],it's a valid bbox ,but in check_bbox,it's a invalid bbox......

## Environment

 - Albumentations version (e.g., 0.1.8):
 - Python version (e.g., 3.7):
 - OS (e.g., Linux):
 - How you installed albumentations ( `pip`):
 - Any other relevant information:

**Comment by albu** [comment]
box is valid if it's coordinates are smaller then image size

**Comment by albu** [comment]
oh, tilted boxes are not supported yet. you can try to emulate them with keypoints

**Comment by GYxiaOH** [comment]
@GYxiaOH  oh thank you，i will try
