### ISSUE TITLE
"image" element in the augmentation is required

### ISSUE THREAD

**Issue by johngull** [albu/albumentations#46]
Currently, you take size of the images with such code:

> params.update({'cols': kwargs['image'].shape[1], 'rows': kwargs['image'].shape[0]})

But that is not always correct. What if user wants to have a list of images to augment as this one: {"image1": image1, "image2": image2}

**Comment by albu** [comment]
Out of the box this library supports image augmentation only by one (probably with mask). If you want to augment a lot of connected images in absolutely the same way - consider writing your own targets but with same processing function.

In case you want to augment batch of images in different way - just use augmentations in `Dataset` and fill this `Dataset` to `DataLoader`.
