### ISSUE TITLE
How to use with pytorch dataloader?

### ISSUE THREAD

**Issue by aegHarkonnen** [albu/albumentations#47]
Can you, please, add an example for pytorch dataloader?

**Comment by ternaus** [comment]
This pipeline may serve as an example:

https://github.com/ternaus/robot-surgery-segmentation/blob/master/dataset.py#L22

**Comment by John1231983** [comment]
Great. If my data loader uses PIL to read image, can I use your method for augmentation? I am working on classification problem

**Comment by ternaus** [comment]
Yes, you can. 

Albumentations work with numpy arrays, hence you will probably need to do the following steps:

```
# Convert PIL image to numpy array
image_np = np.array(image)

# Apply transformations
augmented = transform(image=image_np)

# Convert numpy array to PIL Image
image = Image.fromarray(augmented["image"])
```

**Comment by John1231983** [comment]
Very clear. Just one more question. In pytorch, I am using
```
transforms.Resize((500,500)), transforms.RandomCrop((224, 224)),
```
Which functions should I use in your API to obtain same procedure as the above?

**Comment by creafz** [comment]
@John1231983 In #51 we added Resize augmentation, I have made an example notebook that shows how you can use albumentations instead of torchvision for resizing and cropping images - https://gist.github.com/creafz/a364b21d8625143aa5691e3f7f0347d5

You can install the latest version with Resize augmentation from GitHub: `pip install -U git+https://github.com/albu/albumentations`, we will upload the new version to PyPI soon.

**Comment by John1231983** [comment]
Very good. I have written a class that can be used in pytorch. Feel free to correct it
```
class ImageAug:
    def __init__(self, image_size, p):
        self.aug=Compose([
            RandomCrop(image_size, image_size),
            Flip(),
                Transpose(),
                OneOf([
                    IAAAdditiveGaussianNoise(),
                    GaussNoise(),
                ], p=0.1),
                OneOf([
                    MotionBlur(p=.2),
                    MedianBlur(blur_limit=3, p=.1),
                    Blur(blur_limit=3, p=.1),
                ], p=0.1),
                ShiftScaleRotate(shift_limit=0.0625, scale_limit=0.2, rotate_limit=20, p=.2),
                OneOf([
                    OpticalDistortion(p=0.3),
                    GridDistortion(p=.1),
                    IAAPiecewiseAffine(p=0.3),
                ], p=0.1),
                OneOf([
                    CLAHE(clip_limit=2),
                    RandomContrast(),
                    RandomBrightness(),
                ], p=0.3),
                HueSaturationValue(p=0.3),
            ], p=p)

    def __call__(self, img):
        img = np.array(img)
        img = self.aug(image=img)['image']
        return Image.fromarray(img)

```
In pytorch, it is
```
torchvision_transform = transforms.Compose([
    transforms.Scale((500, 500)),
    ImageAug (224,0.5)
    transforms.RandomHorizontalFlip()
])
```
