### ISSUE TITLE
Off-by-one error in x_max/y_max when cropping

### ISSUE THREAD

**Issue by cxz** [albu/albumentations#48]
There's an off-by-one in this check (line 103) and how the slicing is done ```img[y_min:y_max, x_min:x_max]```.

https://github.com/albu/albumentations/blob/1722c44adb1f66ec25103fde1a186c8fcb86bf81/albumentations/augmentations/functional.py#L103

Forcing x_max < width and y_max < height means we always crop the right-most column and bottom-most line.

**Comment by ternaus** [comment]
Thank you. 

Fixed in https://github.com/albu/albumentations/pull/49
