### ISSUE TITLE
Problems with gray images and ToGray function

### ISSUE THREAD

**Issue by bonlime** [albu/albumentations#67]
Can't figure out how to use albumentations for gray images, due to error in functions like RandomContrast which try to cast image to gray => raise an error

And also ToGray is impossible to use in Compose:
```
im = np.random.randint(0,255,(224,224,3))
aug = Compose([ToGray(p=1.)],p=1.)
augmented = ToGray()(image = im) # works
augmented2 = aug(image=im) # fails with opencv error:

Unsupported depth of input image:
>     'VDepth::contains(depth)'
> where
>     'depth' is 4 (CV_32S)
```
it looks like the problem is due to cast from `int8` to `float32` before calling this transform

**Comment by bonlime** [comment]
The workaround to use gray images: stack 3 of the same image, to make an img of shape (224,224,3), augment, then take slice of the result

**Comment by johngull** [comment]
Have the same issue when using RandomContrast and CLAHE.
The reason of problem is `gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)` without checking type of images

**Comment by johngull** [comment]
I solved it with 2 additional transformations:

```
from albumentations import ImageOnlyTransform
import cv2

class GrayToRGB(ImageOnlyTransform):
    """
    Targets:
        image

    Image types:
        uint8, float32
    """

    def __init__(self, p=1.0):
        super(GrayToRGB, self).__init__(p)

    def apply(self, img, **params):
        return cv2.cvtColor(img, cv2.COLOR_GRAY2RGB)


class RGBToGray(ImageOnlyTransform):
    """
    Targets:
        image

    Image types:
        uint8, float32
    """

    def __init__(self, p=1.0):
        super(RGBToGray, self).__init__(p)

    def apply(self, img, **params):
        return cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
```

Shall I add such pull request? Or this is out of normal usage for your library?

**Comment by BloodAxe** [comment]
Albumentations relies on OpenCV for colorspace conversion. In OpenCV conventional ranges for R, G, and B channel values are:

```
0 to 255 for CV_8U images
0 to 65535 for CV_16U images
0 to 1 for CV_32F images
```
Therefore if your image has values from [0..255] range you may want to convert it to `uint8` dtype explicitly: `im = np.random.randint(0,255,(224,224,3)).astype(np.uint8)`.
