### ISSUE TITLE
Git-less installation recommendation in readme

### ISSUE THREAD

**Issue by adler-j** [albu/albumentations#86]
The current recommended way to install is

    pip install -U git+https://github.com/albu/albumentations

This requires git, something not everyone might have installed (particularly on windows).

If you change it to

    pip install -U https://github.com/albu/albumentations/archive/master.zip

The installation can be done without git.

**Comment by albu** [comment]
We mainly focus on installation from pypi. `pip install albumentation`. Version there updates frequently. Installing from git is mainly for developers
