### ISSUE TITLE
Compose object fails on images without bboxes

### ISSUE THREAD

**Issue by Goorman** [albu/albumentations#89]
Problem lies in these lines: https://github.com/albu/albumentations/blob/3a294a3c993109aaabeca5b4901e90f03f1079ce/albumentations/core/composition.py#L47-L50

If data['bboxes'] is an empty list (or does not exist at all), this code raises error.

**Comment by albu** [comment]
fixed, thanks!

**Comment by sharmalakshay93** [comment]
I am seeing this the same/similar error for images that have no objects in them:

```
  File "/usr/local/lib/python3.6/dist-packages/albumentations/augmentations/bbox_utils.py", line 330, in check_bbox
    "to be in the range [0.0, 1.0], got {value}.".format(bbox=bbox, name=name, value=value)
ValueError: Expected x_min for bbox (tensor(nan), tensor(nan), tensor(nan), tensor(nan), tensor(-9223372036854775808)) to be in the range [0.0, 1.0], got nan.
```

Any advice on how I can fix this? If it helps, I'm following [this](https://www.kaggle.com/meemr5/traffic-light-detection-pytorch-starter) tutorial

**Comment by BloodAxe** [comment]
Please use the issue template that helps to assemble informative request with all the necessary information to reproduce/understand your issue.

**Comment by Dipet** [comment]
Check your bboxes. In error message I see that bbox contains only `NaN` values.
