### ISSUE TITLE
Allow list in `to_tuple()` 

### ISSUE THREAD

**Issue by marcocaccin** [albu/albumentations#90]
**Reason**: building composition of transformations from json file, but json only has list as sequences. 
Example: it would be great to be able to do `RandomScale(scale_limit=[0.5, 3], p=1)`

**Where**: https://github.com/albu/albumentations/blob/3a294a3c993109aaabeca5b4901e90f03f1079ce/albumentations/core/transforms_interface.py#L8

**How**:
```
def to_tuple(param, low=None):
    if isinstance(param, (tuple, list)):
        return tuple(param)
    else:
        return (-param if low is None else low, param)
```
+ a one-liner in the tests, if we fancy so

**Comment by ternaus** [comment]
@marcocaccin Could you please make a PR with this change?

**Comment by marcocaccin** [comment]
Of course, I wrote it here as I was unsure about the feature request etiquette :)
