### ISSUE TITLE
Availability in Anaconda

### ISSUE THREAD

**Issue by npielawski** [albu/albumentations#91]
Hello all,

thanks for working on such a nice project, I have tried imgaug, augmentor and keras, but wasn't satisfied since I am doing a lot of patch segmentation.

I would have wanted to know if it were possible to add albumentations in the repository of Anaconda, so that we could install it and keep track of the versions easily?

Thanks in advance,
Nicolas

**Comment by vfdev-5** [comment]
if nobody is working on this, I can do this like [here](https://github.com/pytorch/ignite/tree/master/conda.recipe)

**Comment by albu** [comment]
that would be great, thanks in advance!

**Comment by vfdev-5** [comment]
@albu I assume you have an account on anaconda: https://anaconda.org/albu

**Comment by albu** [comment]
yes
