### ISSUE TITLE
Setting random seed

### ISSUE THREAD

**Issue by amirbar** [albu/albumentations#93]
Hi,

I've noticed I receive different augmentation results between two identical runs, although my seeds are fixed. I set tensorflow (which shouldn't be related) and numpy random seeds. 

Is there an additional seed needs to be set for albumentations?

Thanks,

**Comment by BloodAxe** [comment]
Hi. Albumentations uses neither numpy random nor tensorflow random. It relies only on python random numbers generator. So to obtain reproducible augmentations you should fix python random seed. That should be enough to get consistent random numbers across runs.

**Comment by nosound2** [comment]
And

```
import imgaug
imgaug.random.seed(123)

```

for IAA transforms, they use a different seed.
